// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch_amalgamated.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise Add, Subtract, Divide, multiply
// ---------------------

TEST_CASE("Add", "[Calculator Class Test]")
{
    Calculator calc;
    REQUIRE(calc.add(1,1) == 2);
}

TEST_CASE("subtract", "[Calculator Class Test]")
{
    Calculator calc;
    REQUIRE(calc.subtract(3,1) == 2);
}

TEST_CASE("multiply", "[Calculator Class Test]")
{
    Calculator calc;
    REQUIRE(calc.mul(3,2) == 6);
}

TEST_CASE("divide", "[Calculator Class Test]")
{
    Calculator calc;
    REQUIRE(calc.divide(4,2) == 2);
}
